In [14]:
# source: https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb#scrollTo=SfR4MsSDU880
import tensorflow as tf
import tensorflow.keras as keras
import numpy

In [15]:
# gets inputs
mnist = tf.keras.datasets.fashion_mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [16]:
# setup model
# model has three layers
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)), # input layer
    tf.keras.layers.Dense(128, activation='relu'), # layer 2
    # tf.keras.layers.Dense(64, activation='sigmoid'), # layer 3
    # tf.keras.layers.Dropout(0.2), # randomly sets to 0, prevents overfitting
    tf.keras.layers.Dense(10) # output layer

])

In [17]:
# for each example, model returns a vector of logits (log-odds scores)
# one for each class
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.1709923 ,  0.19350243, -0.18584454,  1.029766  , -1.0878539 ,
        -1.4160498 ,  0.0573594 , -0.7235396 ,  0.70365936,  0.5482729 ]],
      dtype=float32)

In [18]:
# converts logits to probabilities for each class
tf.nn.softmax(predictions).numpy()

array([[0.09965526, 0.10192394, 0.06974738, 0.23521273, 0.02830024,
        0.02038245, 0.08895084, 0.04073896, 0.16975966, 0.14532858]],
      dtype=float32)

In [19]:
# loss fn
# losses.SCC takes a vector of logits and a True index
# returns a scalar loss for each example
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [20]:
loss_fn(y_train[:1], predictions).numpy()

1.9287579

In [22]:
model.compile(optimizer='adam',
                loss=loss_fn,
                metrics=['accuracy']) # todo: what is this?

In [23]:
# approximage the function using the w/b in the model
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.5316 - accuracy: 0.8096
Epoch 2/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.4003 - accuracy: 0.8545
Epoch 3/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.3660 - accuracy: 0.8648
Epoch 4/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.3456 - accuracy: 0.8726
Epoch 5/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3297 - accuracy: 0.8784
Epoch 6/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.3179 - accuracy: 0.8828
Epoch 7/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.3057 - accuracy: 0.8860
Epoch 8/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2975 - accuracy: 0.8904
Epoch 9/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2904 - accuracy: 0.8911
Epoch 10/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.283

In [24]:
# checks performance on test set
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.3406 - accuracy: 0.8799


[0.34064334630966187, 0.8798999786376953]

In [25]:
# returns a probability
# wraps the trained model and attaches softmax to it
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [26]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.2329385e-06, 3.9327280e-10, 4.7750532e-08, 2.1307592e-08,
        1.1621369e-07, 3.2713658e-03, 6.4749349e-07, 2.3966482e-02,
        1.0842544e-06, 9.7275698e-01],
       [8.1987724e-05, 3.5883263e-14, 9.9876308e-01, 2.8882135e-12,
        9.1450964e-04, 1.6702027e-12, 2.4033499e-04, 4.0054764e-16,
        1.5108766e-10, 6.6771661e-18],
       [2.5936768e-09, 1.0000000e+00, 2.0550109e-12, 5.1937787e-10,
        1.7044011e-09, 2.5701170e-21, 3.6207519e-12, 3.5352179e-31,
        1.0957564e-17, 3.8509034e-24],
       [2.9665843e-08, 9.9999964e-01, 5.3524962e-10, 2.0215064e-07,
        7.1618231e-08, 3.3743903e-19, 6.0530259e-10, 3.6091725e-28,
        3.0305185e-15, 6.1778695e-20],
       [8.8540830e-02, 2.8988106e-07, 2.9489208e-02, 9.6477271e-04,
        9.4899954e-04, 6.1553452e-05, 8.7988317e-01, 2.4951577e-08,
        1.1108580e-04, 1.7683693e-07]], dtype=float32)>